### ISSUE TITLE
Out of date issue with GCP Form

### ISSUE THREAD

**Issue by leminhds** [mage-ai/mage-ai-terraform-templates#44]
The GCP terraform files seem to be out of date.

I have the following error
```
Failed to retrieve available versions for module "lb-http" (load_balancer.tf:57) from [registry.terraform.io](http://registry.terraform.io/): failed to
│ request discovery document: Get "https://registry.terraform.io/.well-known/terraform.json": read tcp
```

that issue seems to be fixed when I set lb-http in the laod_balancer.tf file to the latest version: 10.1.0. but then, after doing so, it seems that the minimum required_providers version for google needs to be higher (5.0)

**Comment by wangxiaoyou1993** [comment]
@leminhds i'm not able to reproduce the error. I can use the current scripts to provision GCP deployment successfully.
<img width="599" alt="image" src="https://github.com/mage-ai/mage-ai-terraform-templates/assets/80284865/98a821f6-13fa-4976-82cf-2f9019fb5d52">

**Comment by leminhds** [comment]
hmm it now works for me as well... I will go ahead and close the ticket. Thank you
